# Default values for helm_charts
# Declare values for templates

replicaCount: 3
storage: 20Gi

image:
   repo: ghost
   tag: stable

pod:
  port: 2368

nameOverride: ""
fullnameOverride: ""

service:
  enabled: false
  tier: Frontend
  type: LoadBalancer
  port: 2368

deployments:
  all_apps:
    - api
    - chat

api:
  replicacount: 3



